version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "50011:80"
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.biz_layer==slb
      replicas: 2
      restart_policy:
        condition: on-failure
  # --

  oracle11g:
    image: registry-vpc.cn-shanghai.aliyuncs.com/hmpay/oracle:v1
    ports:
       - "1521:1521"
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.biz_layer==db
    volumes:
      - ~/oracleInstaller:/install
      - ~/oracle_dpdump:/opt/oracle/dpdump
