version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "50011:80"
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.biz_layer==slb
      replicas: 2
      restart_policy:
        condition: on-failure

