version: "3.8"
services:
  # https://hub.docker.com/_/nginx
  nginx:
    image: nginx
    ports:
      - "9011:80"
    # environment:
    #   - NGINX_HOST: "ops"
    deploy:
      mode: global
  # https://hub.docker.com/r/sonatype/nexus3      
  nexus3:
    image: sonatype/nexus3
    ports:
      - "9021:8081"
      - "9022:5000"
    volumes: 
      - ~/volumes/nexus3-data:/nexus-data  
    deploy:
      mode: global
  # https://hub.docker.com/r/jenkinszh/jenkins-zh      
  jenkins:
    image: jenkinszh/jenkins-zh:lts
    ports:
      - "9031:8080"
      - "9032:50000"
    volumes: 
      - ~/volumes/jenkins-data:/var/jenkins_home
    deploy:
      mode: global






